# Generated by Django 5.2.16 on 2026-07-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(blank=True, help_text='The answer/button text that leads here from the parent question (blank for the root).', max_length=120)),
                ('kind', models.CharField(choices=[('question', 'Question (has options)'), ('result', 'Result (who to contact)')], max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('question', models.CharField(blank=True, max_length=200)),
                ('who', models.CharField(blank=True, max_length=250, verbose_name='Who to contact')),
                ('action', models.TextField(blank=True, verbose_name='What to do')),
                ('escalate', models.TextField(blank=True, verbose_name='When/where to escalate')),
                ('keep', models.TextField(blank=True, verbose_name='Evidence to keep')),
                ('email_template', models.TextField(blank=True, help_text="Optional tailored 'first useful email' for this result. Leave blank to auto-generate one from the fields above. Square brackets mark the blanks members fill in.")),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faq.contactnode')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
