# Generated by Django 5.2.16 on 2026-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_seed_contact_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnode',
            name='email_template',
            field=models.TextField(blank=True, help_text="Optional tailored 'first useful email' for this result. Leave blank to auto-generate one from the fields above. Square brackets mark the blanks members fill in — the tokens [name], [College], [course] and [CRSid] are filled in automatically from the logged-in member's profile."),
        ),
    ]
