# Generated by Django 5.2.16 on 2026-07-12 12:56

import django.db.models.deletion
import faq.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_contactnode_email_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=faq.models._school_choices, help_text="Which School's page this contact appears on.", max_length=30)),
                ('department', models.CharField(help_text="e.g. 'Faculty of History — Undergraduate Office'.", max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.CharField(blank=True, help_text="What they handle / when to use this address, e.g. 'timetable clashes and submission extensions'.", max_length=250)),
                ('responds_well', models.BooleanField(default=False, help_text='Tick for offices members report as quick and helpful — they get a ✅ on the public page.', verbose_name='runs well')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_contacts_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', '-responds_well', 'department'],
                'unique_together': {('school', 'department')},
            },
        ),
    ]
