# Generated by Django 5.2.16 on 2026-07-12 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify

RESERVED_SLUGS = {"new", "tags"}


def backfill_event_slugs(apps, schema_editor):
    """Give every existing event its title-and-date slug (mirrors
    Event.build_slug, which historical models don't have)."""
    Event = apps.get_model("events", "Event")
    taken = set(RESERVED_SLUGS)
    for event in Event.objects.order_by("pk"):
        date_part = timezone.localtime(event.start).strftime("%-d-%b-%Y").lower()
        base = slugify(f"{event.title} {date_part}")[:170] or f"event-{date_part}"
        slug, n = base, 2
        while slug in taken:
            slug = f"{base}-{n}"
            n += 1
        taken.add(slug)
        event.slug = slug
        event.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='category',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text="Members who run this club: they can mark their events as official and edit the tag's page.", related_name='tags_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='page_content',
            field=models.TextField(blank=True, help_text="The tag's own page — Markdown and basic HTML supported. Editable by the tag's owners and society admins."),
        ),
        migrations.AddField(
            model_name='event',
            name='attendee_info',
            field=models.TextField(blank=True, help_text="Details for attendees (meeting point, what to bring…) — shown only to people who have RSVP'd. Markdown supported."),
        ),
        migrations.AddField(
            model_name='event',
            name='group_chat_link',
            field=models.URLField(blank=True, help_text="Optional WhatsApp group-chat link, shown only to people who have RSVP'd."),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Who is running the event. Defaults to whoever created it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_hosted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional picture shown on the event page.', upload_to='events/'),
        ),
        # Slug lands in three steps so existing rows don't collide on the
        # unique constraint: add nullable → backfill → enforce unique.
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=180),
        ),
        migrations.RunPython(backfill_event_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Set automatically from the title and date, e.g. winter-ball-12-dec-2026.', max_length=180, unique=True),
        ),
    ]
