# Generated by Django 5.2.16 on 2026-09-04 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_options_category_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_super',
            field=models.BooleanField(default=False, help_text="Super event: a society headline. Shown larger on the calendar, pinned to every member's dashboard, and listed first everywhere. Only super admins can set this."),
        ),
        migrations.AlterField(
            model_name='category',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text="Members who run this club: they manage the tag's events from the panel (promoting them to tagged events), and edit the tag's page. Every tag should have at least one.", related_name='tags_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Tagged event: promoted by the owners of its tag (or a society admin), e.g. an official Supper Club outing. Ranks above ordinary member events, below super events.'),
        ),
    ]
