# Generated by Django 5.2.16 on 2026-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_super_alter_category_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('going', 'Going'), ('waiting', 'On the waitlist'), ('cancelled', 'Not going any more')], default='going', max_length=10),
        ),
    ]
