# Generated by Django 5.2.16 on 2026-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_geocoded_at_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_attendees',
            field=models.BooleanField(default=True, help_text="Show who's going on the event page. The count is always shown."),
        ),
    ]
