# Generated by Django 5.2.16 on 2026-07-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(default='University of Cambridge Mature Student Society', max_length=120)),
                ('short_name', models.CharField(default='MSS', max_length=40)),
                ('tagline', models.CharField(default="Welcoming Cambridge's mature students.", max_length=200)),
                ('about_text', models.TextField(blank=True, help_text='Markdown; shown on the public About page.')),
                ('contact_email', models.EmailField(default='maturesoc@cambridgesu.co.uk', max_length=254)),
                ('mailing_list_address', models.EmailField(default='soc-mss-members@srcf.net', help_text="Where the What's On mailer is sent (SRCF Mailman list).", max_length=254)),
                ('whatsapp_group_link', models.URLField(blank=True, help_text='The group invite link revealed once to each approved member.')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'site configuration',
            },
        ),
    ]
