# Generated by Django 5.2.16 on 2026-07-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_api_key',
            field=models.CharField(blank=True, help_text='API key for the transactional email provider. Stored server-side and never shown in full once saved.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_tone',
            field=models.TextField(blank=True, help_text='Tone-of-voice instructions for anyone (or anything) drafting society emails — shown alongside the mailer.'),
        ),
    ]
