# Generated by Django 5.2.16 on 2026-07-12 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_email_api_key_siteconfig_email_tone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_ai_engine',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('gemini', 'Google (Gemini)'), ('mistral', 'Mistral')], default='deepseek', help_text='Which AI engine drafts society emails (uses the API key above).', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tab_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('content', models.TextField(help_text='Markdown and basic HTML supported.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished pages are visible to admins only.')),
                ('nav_label', models.CharField(blank=True, help_text='Short label for the navigation bar (blank = not in nav).', max_length=30)),
                ('nav_visibility', models.CharField(choices=[('public', 'Everyone (including logged-out visitors)'), ('members', 'Members only'), ('admins', 'Admins only'), ('hidden', 'Hidden from the navigation')], default='public', help_text="Who sees it in the navigation (the page itself follows 'published' plus this audience).", max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_pages_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
