# Generated by Django 5.2.16 on 2026-09-04 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_email_ai_engine_siteconfig_tab_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Version number. The highest published version is the one members must accept.', unique=True)),
                ('title', models.CharField(default='Terms and Conditions', max_length=140)),
                ('content', models.TextField(help_text='Markdown supported: headings, links, lists, emphasis.')),
                ('change_note', models.CharField(blank=True, help_text="What changed in this version, for the committee's own records, e.g. 'Added photography consent clause'.", max_length=250)),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished drafts are visible to admins only and are never shown to members for acceptance.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'terms version',
                'verbose_name_plural': 'terms versions',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='TermsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField(blank=True)),
                ('change_note', models.CharField(blank=True, max_length=250)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('deleted', 'Deleted')], default='edited', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_revisions', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.termsversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('terms_title', models.CharField(blank=True, max_length=140)),
                ('source', models.CharField(choices=[('portal', 'Accepted in the portal'), ('waitlist', 'Accepted on the waitlist form')], default='portal', max_length=10)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptances', to='core.termsversion')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'version_number'), name='unique_terms_acceptance_per_user_version')],
            },
        ),
    ]
