# Generated by Django 5.2.16 on 2026-10-02 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfig_messaging_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text="Members who may edit this page's title and content without being admins. Publishing, audience and navigation stay with admins.", related_name='site_pages_editable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SitePageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('restored', 'Restored')], default='edited', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_page_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.sitepage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
