# Generated by Django 5.2.16 on 2026-10-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitepage_editors_and_revisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(max_length=60)),
                ('blurb', models.CharField(max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True, help_text='Untick when someone steps down.')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_text',
            field=models.TextField(blank=True, help_text='Markdown. Leave blank for no banner.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_until',
            field=models.DateTimeField(blank=True, help_text='Hide the banner after this time.', null=True),
        ),
    ]
