# Generated by Django 5.2.16 on 2026-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_committee_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='easter_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='lent_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='michaelmas_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
