# Generated by Django 5.2.16 on 2026-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_term_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='geoapify_api_key',
            field=models.CharField(blank=True, help_text='Geoapify key for the poster map and venue look-ups. Stored server-side; blank means posters show a directions QR code instead of a map.', max_length=80),
        ),
    ]
