# Generated by Django 5.2.16 on 2026-10-08 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_geoapify_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='section',
            field=models.CharField(choices=[('about', 'About'), ('guide', 'Guide'), ('members', 'Members portal')], default='about', help_text='Which menu the page sits under, when it has a navigation label.', max_length=10),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_blocks_edited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
