# Generated by Django 5.2.16 on 2026-07-12 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('section', models.CharField(choices=[('arriving', 'Before you arrive'), ('colleges', 'Colleges for mature students'), ('study', 'Study & academic life'), ('money', 'Money & funding'), ('family', 'Family, partners & children'), ('living', 'Living in Cambridge'), ('social', 'Social life & societies'), ('faq', 'FAQs')], default='living', max_length=20)),
                ('content', models.TextField(help_text='Markdown supported: headings, links, lists, emphasis.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_pages_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_pages_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuideRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='guide.guidepage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
