# Generated by Django 5.2.16 on 2026-10-03 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_event_geocoded_at_event_latitude_event_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('classic', 'Classic'), ('bold', 'Bold'), ('photo', 'Photo')], default='classic', max_length=8)),
                ('size', models.CharField(choices=[('a4', 'A4'), ('a3', 'A3'), ('square', 'Square'), ('story', 'Story')], default='a4', max_length=8)),
                ('accent', models.CharField(choices=[('tag', "The event's tag colour"), ('pine', 'Pine'), ('brick', 'Brick'), ('gold', 'Gold')], default='tag', max_length=6)),
                ('use_event_picture', models.BooleanField(default=True, help_text='Untick to leave the picture out (a colour scene is used instead).')),
                ('focal_x', models.FloatField(default=0.5)),
                ('focal_y', models.FloatField(default=0.5)),
                ('headline', models.CharField(blank=True, help_text='Leave blank to use the event title.', max_length=140)),
                ('extra_line', models.CharField(blank=True, help_text='One line of your own, e.g. “£5 on the door” or “bring a friend”.', max_length=60)),
                ('show_map', models.BooleanField(default=True)),
                ('show_qr', models.BooleanField(default=True)),
                ('show_description', models.BooleanField(default=True)),
                ('show_host', models.BooleanField(default=True)),
                ('print_marks', models.BooleanField(default=False, help_text='Add 3 mm bleed and crop marks for a print shop.')),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='events.event')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posters_saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosterScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_scans', to='events.event')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
