# Generated by Django 5.2.16 on 2026-07-12 01:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_type', models.CharField(choices=[('raven', 'Raven (CRSid)'), ('associate', 'Associate (approved guest)')], default='raven', max_length=12)),
                ('crsid', models.CharField(blank=True, help_text='Cambridge CRSid, e.g. dbj25. Set automatically by Raven login.', max_length=16, null=True, unique=True)),
                ('college', models.CharField(blank=True, choices=[('christs', "Christ's"), ('churchill', 'Churchill'), ('clare', 'Clare'), ('clare-hall', 'Clare Hall'), ('corpus', 'Corpus Christi'), ('darwin', 'Darwin'), ('downing', 'Downing'), ('emmanuel', 'Emmanuel'), ('fitzwilliam', 'Fitzwilliam'), ('girton', 'Girton'), ('gonville-caius', 'Gonville & Caius'), ('homerton', 'Homerton'), ('hughes-hall', 'Hughes Hall'), ('jesus', 'Jesus'), ('kings', "King's"), ('lucy-cavendish', 'Lucy Cavendish'), ('magdalene', 'Magdalene'), ('murray-edwards', 'Murray Edwards'), ('newnham', 'Newnham'), ('pembroke', 'Pembroke'), ('peterhouse', 'Peterhouse'), ('queens', "Queens'"), ('robinson', 'Robinson'), ('selwyn', 'Selwyn'), ('sidney-sussex', 'Sidney Sussex'), ('st-catharines', "St Catharine's"), ('st-edmunds', "St Edmund's"), ('st-johns', "St John's"), ('trinity', 'Trinity'), ('trinity-hall', 'Trinity Hall'), ('wolfson', 'Wolfson'), ('other', 'Other / staff / not collegiate')], max_length=32)),
                ('mobile', models.CharField(blank=True, help_text='Used for WhatsApp group adds and event organiser contact. Only visible to admins and to organisers of events you RSVP to.', max_length=24)),
                ('photo', models.ImageField(blank=True, upload_to='profiles/')),
                ('is_portal_admin', models.BooleanField(default=False, help_text='Society admin: can approve members, manage events, send mailers.')),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_link_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=24)),
                ('connection', models.TextField(help_text="Their connection to the society, e.g. 'Partner of Jane Smith (Wolfson)'.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_request', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('handled', 'Handled'), ('declined', 'Declined')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
