# Generated by Django 5.2.16 on 2026-07-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="A short 'about me' shown on your member profile.", max_length=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_messages',
            field=models.BooleanField(default=True, help_text='Untick to mute this member: they can read messages but not send.'),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, help_text="What you're studying (or your role), e.g. 'MPhil History of Science'.", max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shadow_banned',
            field=models.BooleanField(default=False, help_text='Shadow ban: the member can use the site normally, but their events and messages are invisible to everyone else.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Super admin: can appoint/remove admins, manage tags and site-wide email settings. Normally just the webmaster.'),
        ),
        migrations.AddField(
            model_name='user',
            name='shadow_banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
