# Generated by Django 5.2.16 on 2026-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grant_dbj25_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, help_text="Hobbies and interests, e.g. 'hill walking, chess, amateur radio'.", max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='talk_to_me_about',
            field=models.CharField(blank=True, help_text="Conversation starters, e.g. 'the Civil War, sourdough, returning to study at 40'.", max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, help_text="What you do or did before Cambridge, e.g. '15 years in supply-chain logistics'.", max_length=200),
        ),
    ]
