# Generated by Django 5.2.16 on 2026-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_interests_user_talk_to_me_about_user_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_version',
            field=models.PositiveIntegerField(blank=True, help_text='Highest version of the terms this member has accepted.', null=True),
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='terms_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
