# Generated by Django 5.2.16 on 2026-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_messaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
    ]
