# Generated by Django 5.2.16 on 2026-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_calendar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_mailer',
            field=models.BooleanField(default=True, help_text="The society's round-up of what's on, sent by the committee now and then.", verbose_name="Email me the What's On mailer"),
        ),
    ]
