# Generated by Django 5.2.16 on 2026-10-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_is_super_alter_category_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('venue', 'Where should it be?'), ('date', 'When should it be?'), ('general', 'A question for members'), ('volunteers', 'Volunteers needed')], max_length=12)),
                ('question', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, help_text='Optional context. Markdown supported.')),
                ('closes_at', models.DateTimeField(help_text='Voting stops at this time. Venue and date polls then set the event automatically.')),
                ('allow_multiple', models.BooleanField(default=False, help_text='Let people pick more than one option.')),
                ('show_results', models.CharField(choices=[('always', 'Always visible'), ('after_vote', 'After you have voted'), ('after_close', 'Only once the poll closes')], default='always', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('needs_decision', models.BooleanField(default=False, help_text='Closed on a tie: the host must pick the winner.')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='events.event')),
            ],
            options={
                'ordering': ['closes_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('start', models.DateTimeField(blank=True, help_text='Date polls: the proposed start.', null=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Volunteer slots: how many people are needed.', null=True)),
                ('is_opt_out', models.BooleanField(default=False, help_text='“None of these” — never wins.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='outcome_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polls.polloption'),
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('option', 'user')},
            },
        ),
    ]
