from django.urls import path

from . import views

app_name = "panel"

urlpatterns = [
    path("", views.home, name="home"),
    path("waitlist/", views.waitlist, name="waitlist"),
    path("waitlist/<int:pk>/review/", views.waitlist_review, name="waitlist_review"),
    path("members/", views.members, name="members"),
    path("members/<int:pk>/edit/", views.member_edit, name="member_edit"),
    path("members/<int:pk>/toggle-admin/", views.member_toggle_admin, name="member_toggle_admin"),
    path("members/<int:pk>/ban/", views.member_ban, name="member_ban"),
    path("members/<int:pk>/unban/", views.member_unban, name="member_unban"),
    path("members/<int:pk>/shadow-ban/", views.member_shadow_ban, name="member_shadow_ban"),
    path("members/<int:pk>/shadow-unban/", views.member_shadow_unban, name="member_shadow_unban"),
    path("members/<int:pk>/toggle-mute/", views.member_toggle_mute, name="member_toggle_mute"),
    path("members/<int:pk>/delete/", views.member_delete, name="member_delete"),
    path("members/<int:pk>/reset-whatsapp/", views.member_reset_whatsapp, name="member_reset_whatsapp"),
    path("events/", views.events_admin, name="events"),
    path("events/<int:pk>/action/", views.event_action, name="event_action"),
    path("messages/", views.messages_admin, name="messages"),
    path("messages/<int:pk>/remove/", views.message_remove, name="message_remove"),
    path("whatsapp/", views.whatsapp_requests, name="whatsapp_requests"),
    path("whatsapp/settings/", views.whatsapp_settings, name="whatsapp_settings"),
    path("whatsapp/<int:pk>/handle/", views.whatsapp_handle, name="whatsapp_handle"),
    path("content/", views.content, name="content"),
    path("content/pages/new/", views.page_create, name="page_create"),
    path("content/pages/<int:pk>/", views.page_edit, name="page_edit"),
    path("content/pages/<int:pk>/delete/", views.page_delete, name="page_delete"),
    path("content/dept-contacts/new/", views.dept_contact_add, name="dept_contact_add"),
    path("content/dept-contacts/<int:pk>/", views.dept_contact_edit, name="dept_contact_edit"),
    path("content/dept-contacts/<int:pk>/delete/", views.dept_contact_delete, name="dept_contact_delete"),
    path("content/contact-map/", views.contact_map, name="contact_map"),
    path("content/contact-map/add/", views.contact_node_add, name="contact_node_add"),
    path("content/contact-map/<int:pk>/", views.contact_node_edit, name="contact_node_edit"),
    path("content/contact-map/<int:pk>/delete/", views.contact_node_delete, name="contact_node_delete"),
    path("terms/", views.terms, name="terms"),
    path("terms/new/", views.terms_create, name="terms_create"),
    path("terms/<int:pk>/", views.terms_edit, name="terms_edit"),
    path("terms/<int:pk>/delete/", views.terms_delete, name="terms_delete"),
    path("terms/<int:pk>/acceptances/", views.terms_acceptances, name="terms_acceptances"),
    path("stats/", views.stats, name="stats"),
    path("mailer/", views.mailer, name="mailer"),
    path("audit/", views.audit, name="audit"),
    # Super admin (webmaster) only.
    path("super/", views.superadmin, name="superadmin"),
    path("super/email/", views.superadmin_email, name="superadmin_email"),
    path("super/tags/new/", views.tag_create, name="tag_create"),
    path("super/tags/<int:pk>/", views.tag_admin_edit, name="tag_admin_edit"),
    path("super/tags/<int:pk>/delete/", views.tag_delete, name="tag_delete"),
]
