# Generated by Django 5.2.16 on 2026-10-02 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('author_college', models.CharField(blank=True, max_length=60)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Shown publicly as “An MSS member”. The committee can still see who wrote it.')),
                ('body', models.TextField(max_length=600)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Published'), ('rejected', 'Not published')], default='pending', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured testimonials lead the page and appear on the homepage.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text="Shown to the member, e.g. why it wasn't published.", max_length=200)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
