# Generated by Django 5.2.16 on 2026-10-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('event', 'Event'), ('poll', 'Poll'), ('waitlist', 'Waitlist'), ('testimonial', 'Testimonial'), ('page', 'Page'), ('general', 'General'), ('survey', 'Survey')], default='general', max_length=12),
        ),
    ]
